version: '3.9'

services:
  server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./conf:/app/src

    command: >
      sh -c "python3 /app/src/manage.py makemigrations   &&
            /app/src/manage.py migrate  &&
            /app/src/manage.py test &&
            /app/src/manage.py runserver 0:8000"
          

    depends_on:
      # - haji_db
      - haji_redis
      # - haji_rabbit
      # - haji_mongo

  # haji_db:
  #   container_name: haji_db
  #   image: mdillon/postgis:11
  #   restart: always

  # haji_mongo:
  #   container_name: haji_mongo
  #   image: mongo:5.0
  #   restart: always

  # haji_celery:
  #   container_name: haji_celery
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   working_dir: /app/src
  #   command: ["celery", "-A", "haji", "worker", "-l", "info"]
  #   restart: always
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - server

  # haji_beat:
  #   container_name: haji_beat
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   working_dir: /app/src
  #   command: ["celery", "-A", "haji", "beat", "-l", "info"]
  #   restart: always
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - server

  haji_redis:
    container_name : haji_redis

    image: redis:5.0.8
    restart: always

  # haji_rabbit:
  #   container_name : haji_rabbit
  #   image: rabbitmq:3.9
  #   restart: always

  # daphne -b 0.0.0.0 -p 8000 haji.asgi:application